#!/bin/sh
#
# tutatuta
#
# chkconfig:   - 80 20
# description: nekopeko server

### BEGIN INIT INFO
# Provides: tutatuta
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Stop: 0 1 6
# Short-Description: nekopeko server
# Description: nekopeko server
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

nohup node /home/an_nodejs/tutatuta_v0.2/server.js >> /home/an_nodejs/tutatuta_v0.2/nekopeko.log 2>&1&
